#!/usr/bin/env bash
###############################################################################
# setup-codex-nemotron-gitbash.sh   (Windows + Git Bash)
#
# Installs OpenAI Codex CLI and points it DIRECTLY at NVIDIA's
# OpenAI-compatible endpoint, so your coding agent runs on Nemotron.
# No proxy needed — Codex speaks the OpenAI format natively.
#
#     Codex CLI -> https://integrate.api.nvidia.com/v1 -> Nemotron
#
# Usage (in Git Bash):
#   chmod +x setup-codex-nemotron-gitbash.sh
#   ./setup-codex-nemotron-gitbash.sh
###############################################################################
set -euo pipefail

DEFAULT_MODEL="nvidia/nemotron-3-ultra-550b-a55b"
INVOKE_BASE="https://integrate.api.nvidia.com/v1"
CODEX_HOME="$HOME/.codex"
LAUNCH_DIR="$HOME/.codex-nemotron"

info()  { printf "\033[1;34m[INFO]\033[0m %s\n"  "$1"; }
ok()    { printf "\033[1;32m[ OK ]\033[0m %s\n"  "$1"; }
fail()  { printf "\033[1;31m[FAIL]\033[0m %s\n"  "$1"; exit 1; }

case "$(uname -s)" in
  MINGW*|MSYS*|CYGWIN*) : ;;
  *) info "This looks like a non-Windows shell. Continuing anyway, but this script targets Git Bash on Windows." ;;
esac

# ---------------------------------------------------------------- user input
echo ""
if [[ -n "${NVIDIA_API_KEY:-}" ]]; then
  info "Using NVIDIA_API_KEY already set in your environment."
else
  read -r -s -p "Paste your NVIDIA API key (nvapi-...): " NVIDIA_API_KEY
  echo ""
fi
[[ -n "$NVIDIA_API_KEY" ]] || fail "API key cannot be empty."
[[ "$NVIDIA_API_KEY" == nvapi-* ]] || info "Key doesn't start with 'nvapi-' — continuing anyway, double-check it."

read -r -p "Model ID [default: $DEFAULT_MODEL]: " MODEL_ID
MODEL_ID="${MODEL_ID:-$DEFAULT_MODEL}"

# ---------------------------------------------------------------- Node.js
if ! command -v node >/dev/null 2>&1; then
  info "Node.js not found. Trying winget..."
  if command -v winget.exe >/dev/null 2>&1; then
    winget.exe install --id OpenJS.NodeJS.LTS -e --accept-source-agreements --accept-package-agreements || true
    fail "Node.js was just installed. CLOSE this Git Bash window, open a NEW one, and re-run this script."
  else
    fail "Install Node.js LTS from https://nodejs.org, then re-run this script in a new Git Bash window."
  fi
fi
ok "Node.js $(node --version) ready."

# ---------------------------------------------------------------- Codex CLI
if ! command -v codex >/dev/null 2>&1; then
  info "Installing OpenAI Codex CLI (@openai/codex)..."
  npm install -g @openai/codex
fi
ok "Codex CLI installed."

# ---------------------------------------------------------------- Codex config
mkdir -p "$CODEX_HOME"

# Back up any existing config rather than clobbering it
if [[ -f "$CODEX_HOME/config.toml" ]]; then
  BACKUP="$CODEX_HOME/config.toml.bak.$(date +%Y%m%d%H%M%S)"
  cp "$CODEX_HOME/config.toml" "$BACKUP"
  info "Existing Codex config backed up to: $BACKUP"
fi

info "Writing Codex config with NVIDIA as a custom model provider..."
cat > "$CODEX_HOME/config.toml" <<EOF
# Generated by setup-codex-nemotron-gitbash.sh
# Docs: https://github.com/openai/codex (see docs/config.md for latest keys)

model = "${MODEL_ID}"
model_provider = "nvidia"

[model_providers.nvidia]
name = "NVIDIA NIM"
base_url = "${INVOKE_BASE}"
env_key = "NVIDIA_API_KEY"
# NVIDIA NIM implements the classic Chat Completions API, not the Responses API
wire_api = "chat"
EOF
ok "Codex config written to $CODEX_HOME/config.toml"

# ---------------------------------------------------------------- key storage + launcher
mkdir -p "$LAUNCH_DIR"
cat > "$LAUNCH_DIR/env.sh" <<EOF
export NVIDIA_API_KEY="${NVIDIA_API_KEY}"
EOF
chmod 600 "$LAUNCH_DIR/env.sh"

cat > "$LAUNCH_DIR/codex-nemotron.sh" <<EOF
#!/usr/bin/env bash
source "\$HOME/.codex-nemotron/env.sh"
exec codex "\$@"
EOF
chmod +x "$LAUNCH_DIR/codex-nemotron.sh"

# Optional convenience: offer to persist the key in ~/.bashrc so plain
# 'codex' works in any Git Bash window without the wrapper.
echo ""
read -r -p "Also add NVIDIA_API_KEY to your ~/.bashrc so plain 'codex' works everywhere? [y/N]: " ADD_RC
if [[ "${ADD_RC,,}" == "y" ]]; then
  if ! grep -q "NVIDIA_API_KEY" "$HOME/.bashrc" 2>/dev/null; then
    printf '\n# NVIDIA NIM key for Codex CLI\nexport NVIDIA_API_KEY="%s"\n' "$NVIDIA_API_KEY" >> "$HOME/.bashrc"
    ok "Added to ~/.bashrc (takes effect in new Git Bash windows)."
  else
    info "~/.bashrc already mentions NVIDIA_API_KEY — left it untouched."
  fi
fi

# ---------------------------------------------------------------- smoke test
info "Testing your key against the NVIDIA endpoint..."
HTTP_CODE=$(curl -sS -o "$LAUNCH_DIR/last-test.json" -w "%{http_code}" \
  --request POST \
  --url "${INVOKE_BASE}/chat/completions" \
  --header "Authorization: Bearer ${NVIDIA_API_KEY}" \
  --header "Content-Type: application/json" \
  --data "{\"model\": \"${MODEL_ID}\", \"messages\": [{\"role\":\"user\",\"content\":\"Say OK\"}], \"max_tokens\": 10, \"stream\": false}" ) || true

if [[ "$HTTP_CODE" == "200" ]]; then
  ok "API key and model ID verified (HTTP 200)."
else
  info "Test call returned HTTP ${HTTP_CODE}. Response saved to $LAUNCH_DIR/last-test.json"
  info "Common causes: wrong model ID, expired key, exhausted free credits. Config was still written."
fi

ok "Setup complete!"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo " HOW TO USE (Git Bash) — no proxy, single window"
echo "─────────────────────────────────────────────────────────────"
echo "   Launch Codex on Nemotron:"
echo "     ~/.codex-nemotron/codex-nemotron.sh"
echo ""
echo "   (Or plain 'codex' if you added the key to ~/.bashrc.)"
echo ""
echo "   Change model later: edit 'model = ...' in ~/.codex/config.toml"
echo "   If Codex errors on the config, its keys may have changed —"
echo "   check https://github.com/openai/codex docs/config.md"
echo "─────────────────────────────────────────────────────────────"
